### PR TITLE
Avoid narrowing cast in switch case

### PR DESCRIPTION
**Pull request by mortenfyhn**
`case -1` when the switch variable is uint32_t does not compile with C++11,
and is probably not a good idea anyway. As far as I can tell, casting -1
to unsigned gives the max unsigned value, so I replaced the -1 with UINT32_MAX.
That might be platform-dependent and I'm not even sure if it's defined
behaviour.

I'm building on ~kinetic~ melodic, which uses C++11 by default, hence the issue.

### CODE REVIEW

**Comment by pl-kabaradjian** [comment]
You are correct this is not optimal. I don't know if UINT32_MAX is universal though, we can put 0xffffffff to be sure.

**Comment by mortenfyhn** [comment]
Absolutely, `0xffffffff` should be good.

**Comment by pl-kabaradjian** [comment]
Added. Please confirm if good for you, then I will merge.

**Comment by mortenfyhn** [comment]
All good, go ahead and merge!

**Pull request merged**
